apiVersion: v1
kind: Pod
metadata: 
  name: kubia-liveness
spec:
  containers:
  - image: burkovski/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
